name: status
on:
  push:
    branches: [ main, feat/**, chore/** ]
  schedule:
    - cron: "0 0 * * *"  # daily UTC
permissions:
  contents: write
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          make all
          make status
      - name: Commit updated tracker (if changed)
        run: |
          git config user.name "fogbreaker-status-bot"
          git config user.email "actions@users.noreply.github.com"
          git diff --quiet || (git add docs/NOW_NEXT.md && git commit -m "chore: auto-update NOW/NEXT" && git push)
